version: "3.3"
services:
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/src/evanduke/static

  nginx:
    build: nginx
    restart: always
    volumes:
      - static_volume:/src/evanduke/static
    depends_on:
      - web
    ports:
      - "80:80"


volumes:
  static_volume:
