# syntax=docker/dockerfile:1

FROM python:3.11-alpine

ENV POETRY_VERSION=1.6.1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Install curl and poetry
RUN apk add --no-cache curl \
    && curl -sSL https://install.python-poetry.org | POETRY_VERSION=$POETRY_VERSION python3 -

# Expose the Django port
EXPOSE 8000

# Set the working directory
WORKDIR /app

# Copy the project files
COPY . .

# Install the dependencies and manage static files
RUN /root/.local/bin/poetry config virtualenvs.create false \
    && /root/.local/bin/poetry install --only main --no-root

#RUN pip install --index-url=URL_OF_YOUR_PYPI_SERVER evanduke==VERSION \
#    && /root/.local/bin/poetry config virtualenvs.create false \
#    && /root/.local/bin/poetry install --only main --no-root

#CMD python manage.py runserver 0.0.0.0:8000
ENTRYPOINT ["/app/entrypoint-dev.sh"]
