# syntax=docker/dockerfile:1

FROM python:3.10-alpine

ENV POETRY_VERSION=1.2.2 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apk add --no-cache curl \
    && curl -sSL https://install.python-poetry.org | POETRY_VERSION=$POETRY_VERSION python3 -

EXPOSE 8080

WORKDIR /src

COPY . .

RUN /root/.local/bin/poetry config virtualenvs.create false && /root/.local/bin/poetry install --only main

ENTRYPOINT ["gunicorn", "--bind", "localhost:8080", "--access-logfile", "-", "app:app"]
