version: "3.3"
services:
  web:
    image: hnduke/evanduke:latest
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - etc/evanduke/.storage:/etc/evanduke/.storage
    ports:
      - "8080:8080"
    networks:
      - evanduke-network

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - static_volume:/static
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - evanduke-network

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_volume:

networks:
  evanduke-network:
    driver: bridge
