version: "3.3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-dev-dev
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - evanduke-network

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.dev.conf
    depends_on:
      - web
    ports:
      - "80:80"
    networks:
      - evanduke-network

networks:
  evanduke-network:
    driver: bridge
