version: "3.3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-app-dev
    restart: always
    volumes:
      - static_volume:/src/evanduke/static
    ports:
      - "8080:80"

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile-nginx-dev
    restart: always
    volumes:
      - static_volume:/src/evanduke/static
    depends_on:
      - web
    ports:
      - "80:80"


volumes:
  static_volume:
