version: "3.3"
services:
  web:
    image: hnduke/evanduke:latest
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8080:8080"
    networks:
      - evanduke-network

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - static_volume:/static
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    ports:
      - "80:80"
    networks:
      - evanduke-network

volumes:
  static_volume:

networks:
  evanduke-network:
    driver: bridge
