# Generated by Django 4.2.4 on 2023-08-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enterprises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrequentlyAskedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("ordering", models.IntegerField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("Fractional Management", "FRACTIONAL_MANAGEMENT"),
                            ("Consultations", "CONSULTATIONS"),
                        ],
                        default="Fractional Management",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
