# Generated by Django 4.2.4 on 2023-08-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enterprises", "0003_add_faq_ordering_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactformsubmission",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contactformsubmission",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contactformsubmission",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactformsubmission",
            name="submitted_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
